-- AlterTable
ALTER TABLE "Family" ADD COLUMN     "billLeadMinutes" INTEGER[] DEFAULT ARRAY[4320, 1440]::INTEGER[],
ADD COLUMN     "digestDays" INTEGER[] DEFAULT ARRAY[1, 2, 3, 4, 5, 6, 7]::INTEGER[],
ADD COLUMN     "digestEveryEvening" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "documentLeadMinutes" INTEGER[] DEFAULT ARRAY[86400, 43200, 10080]::INTEGER[],
ADD COLUMN     "eventLeadMinutes" INTEGER[] DEFAULT ARRAY[10080, 1440, 120]::INTEGER[],
ADD COLUMN     "taskLeadMinutes" INTEGER[] DEFAULT ARRAY[1440]::INTEGER[];

